Update platformio.py
if has lib directory, and set ProcessUnFlags, will crash by message
TypeError: unhashable type: 'NodeList':

because lib's file a list, so call set function will be crashed