Add __attribute__((unused)) to generated test code
Without this, the compiler will generate unused parameter warnings in
the native version:

test/output_export.cpp: In function ‘void output_start(unsigned int)’:
test/output_export.cpp:6:32: error: unused parameter ‘baudrate’ [-Werror=unused-parameter]
 void output_start(unsigned int baudrate)
                                ^~~~~~~~
cc1plus: all warnings being treated as errors